// Generated from Overworld.tmx by scripts/build-tiled-overworld.py. Do not edit.
import { MapActableDef, MapCollisionRect, MapEncounterZone, MapPoint, MapPortalDef, MapSpawnDef, MapWarpDef } from "./OverworldMapTypes";

export const TILED_COLLISION_RECTS: MapCollisionRect[] = [
	{ x: 0, y: 0, width: 56, height: 1, label: "obstacle" },
	{ x: 0, y: 1, width: 56, height: 1, label: "obstacle" },
	{ x: 0, y: 2, width: 56, height: 1, label: "obstacle" },
	{ x: 0, y: 3, width: 2, height: 1, label: "obstacle" },
	{ x: 3, y: 3, width: 7, height: 1, label: "obstacle" },
	{ x: 17, y: 3, width: 1, height: 1, label: "obstacle" },
	{ x: 27, y: 3, width: 6, height: 1, label: "obstacle" },
	{ x: 43, y: 3, width: 13, height: 1, label: "obstacle" },
	{ x: 0, y: 4, width: 2, height: 1, label: "obstacle" },
	{ x: 3, y: 4, width: 7, height: 1, label: "obstacle" },
	{ x: 12, y: 4, width: 3, height: 1, label: "obstacle" },
	{ x: 17, y: 4, width: 1, height: 1, label: "obstacle" },
	{ x: 20, y: 4, width: 6, height: 1, label: "obstacle" },
	{ x: 27, y: 4, width: 6, height: 1, label: "obstacle" },
	{ x: 34, y: 4, width: 7, height: 1, label: "obstacle" },
	{ x: 43, y: 4, width: 2, height: 1, label: "obstacle" },
	{ x: 53, y: 4, width: 3, height: 1, label: "obstacle" },
	{ x: 0, y: 5, width: 2, height: 1, label: "obstacle" },
	{ x: 3, y: 5, width: 7, height: 1, label: "obstacle" },
	{ x: 12, y: 5, width: 3, height: 1, label: "obstacle" },
	{ x: 20, y: 5, width: 6, height: 1, label: "obstacle" },
	{ x: 27, y: 5, width: 6, height: 1, label: "obstacle" },
	{ x: 34, y: 5, width: 7, height: 1, label: "obstacle" },
	{ x: 43, y: 5, width: 2, height: 1, label: "obstacle" },
	{ x: 53, y: 5, width: 3, height: 1, label: "obstacle" },
	{ x: 0, y: 6, width: 2, height: 1, label: "obstacle" },
	{ x: 3, y: 6, width: 7, height: 1, label: "obstacle" },
	{ x: 12, y: 6, width: 3, height: 1, label: "obstacle" },
	{ x: 20, y: 6, width: 21, height: 1, label: "obstacle" },
	{ x: 43, y: 6, width: 2, height: 1, label: "obstacle" },
	{ x: 53, y: 6, width: 3, height: 1, label: "obstacle" },
	{ x: 0, y: 7, width: 2, height: 1, label: "obstacle" },
	{ x: 3, y: 7, width: 3, height: 1, label: "obstacle" },
	{ x: 7, y: 7, width: 3, height: 1, label: "obstacle" },
	{ x: 12, y: 7, width: 3, height: 1, label: "obstacle" },
	{ x: 19, y: 7, width: 11, height: 1, label: "obstacle" },
	{ x: 31, y: 7, width: 9, height: 1, label: "obstacle" },
	{ x: 43, y: 7, width: 1, height: 1, label: "obstacle" },
	{ x: 53, y: 7, width: 3, height: 1, label: "obstacle" },
	{ x: 0, y: 8, width: 2, height: 1, label: "obstacle" },
	{ x: 19, y: 8, width: 4, height: 1, label: "obstacle" },
	{ x: 24, y: 8, width: 2, height: 1, label: "obstacle" },
	{ x: 34, y: 8, width: 3, height: 1, label: "obstacle" },
	{ x: 38, y: 8, width: 2, height: 1, label: "obstacle" },
	{ x: 43, y: 8, width: 1, height: 1, label: "obstacle" },
	{ x: 53, y: 8, width: 3, height: 1, label: "obstacle" },
	{ x: 0, y: 9, width: 2, height: 1, label: "obstacle" },
	{ x: 43, y: 9, width: 1, height: 1, label: "obstacle" },
	{ x: 53, y: 9, width: 3, height: 1, label: "obstacle" },
	{ x: 0, y: 10, width: 2, height: 1, label: "obstacle" },
	{ x: 43, y: 10, width: 1, height: 1, label: "obstacle" },
	{ x: 53, y: 10, width: 3, height: 1, label: "obstacle" },
	{ x: 0, y: 11, width: 2, height: 1, label: "obstacle" },
	{ x: 4, y: 11, width: 5, height: 1, label: "obstacle" },
	{ x: 11, y: 11, width: 5, height: 1, label: "obstacle" },
	{ x: 20, y: 11, width: 1, height: 1, label: "obstacle" },
	{ x: 30, y: 11, width: 1, height: 1, label: "obstacle" },
	{ x: 43, y: 11, width: 1, height: 1, label: "obstacle" },
	{ x: 53, y: 11, width: 3, height: 1, label: "obstacle" },
	{ x: 0, y: 12, width: 2, height: 1, label: "obstacle" },
	{ x: 4, y: 12, width: 5, height: 1, label: "obstacle" },
	{ x: 11, y: 12, width: 5, height: 1, label: "obstacle" },
	{ x: 21, y: 12, width: 5, height: 1, label: "obstacle" },
	{ x: 42, y: 12, width: 2, height: 1, label: "obstacle" },
	{ x: 53, y: 12, width: 3, height: 1, label: "obstacle" },
	{ x: 0, y: 13, width: 2, height: 1, label: "obstacle" },
	{ x: 4, y: 13, width: 5, height: 1, label: "obstacle" },
	{ x: 11, y: 13, width: 5, height: 1, label: "obstacle" },
	{ x: 21, y: 13, width: 5, height: 1, label: "obstacle" },
	{ x: 35, y: 13, width: 1, height: 1, label: "obstacle" },
	{ x: 50, y: 13, width: 1, height: 1, label: "obstacle" },
	{ x: 53, y: 13, width: 3, height: 1, label: "obstacle" },
	{ x: 0, y: 14, width: 2, height: 1, label: "obstacle" },
	{ x: 4, y: 14, width: 5, height: 1, label: "obstacle" },
	{ x: 11, y: 14, width: 5, height: 1, label: "obstacle" },
	{ x: 21, y: 14, width: 5, height: 1, label: "obstacle" },
	{ x: 50, y: 14, width: 1, height: 1, label: "obstacle" },
	{ x: 53, y: 14, width: 3, height: 1, label: "obstacle" },
	{ x: 0, y: 15, width: 2, height: 1, label: "obstacle" },
	{ x: 4, y: 15, width: 1, height: 1, label: "obstacle" },
	{ x: 6, y: 15, width: 3, height: 1, label: "obstacle" },
	{ x: 14, y: 15, width: 1, height: 1, label: "obstacle" },
	{ x: 21, y: 15, width: 5, height: 1, label: "obstacle" },
	{ x: 43, y: 15, width: 1, height: 1, label: "obstacle" },
	{ x: 50, y: 15, width: 1, height: 1, label: "obstacle" },
	{ x: 53, y: 15, width: 3, height: 1, label: "obstacle" },
	{ x: 0, y: 16, width: 2, height: 1, label: "obstacle" },
	{ x: 3, y: 16, width: 1, height: 1, label: "obstacle" },
	{ x: 20, y: 16, width: 3, height: 1, label: "obstacle" },
	{ x: 24, y: 16, width: 2, height: 1, label: "obstacle" },
	{ x: 43, y: 16, width: 1, height: 1, label: "obstacle" },
	{ x: 53, y: 16, width: 3, height: 1, label: "obstacle" },
	{ x: 0, y: 17, width: 2, height: 1, label: "obstacle" },
	{ x: 43, y: 17, width: 1, height: 1, label: "obstacle" },
	{ x: 53, y: 17, width: 3, height: 1, label: "obstacle" },
	{ x: 0, y: 18, width: 2, height: 1, label: "obstacle" },
	{ x: 27, y: 18, width: 2, height: 1, label: "obstacle" },
	{ x: 41, y: 18, width: 1, height: 1, label: "obstacle" },
	{ x: 43, y: 18, width: 1, height: 1, label: "obstacle" },
	{ x: 53, y: 18, width: 3, height: 1, label: "obstacle" },
	{ x: 0, y: 19, width: 2, height: 1, label: "obstacle" },
	{ x: 27, y: 19, width: 2, height: 1, label: "obstacle" },
	{ x: 43, y: 19, width: 1, height: 1, label: "obstacle" },
	{ x: 48, y: 19, width: 8, height: 1, label: "obstacle" },
	{ x: 0, y: 20, width: 2, height: 1, label: "obstacle" },
	{ x: 27, y: 20, width: 2, height: 1, label: "obstacle" },
	{ x: 48, y: 20, width: 1, height: 1, label: "obstacle" },
	{ x: 54, y: 20, width: 2, height: 1, label: "obstacle" },
	{ x: 0, y: 21, width: 2, height: 1, label: "obstacle" },
	{ x: 54, y: 21, width: 2, height: 1, label: "obstacle" },
	{ x: 0, y: 22, width: 2, height: 1, label: "obstacle" },
	{ x: 16, y: 22, width: 2, height: 1, label: "obstacle" },
	{ x: 54, y: 22, width: 2, height: 1, label: "obstacle" },
	{ x: 0, y: 23, width: 2, height: 1, label: "obstacle" },
	{ x: 4, y: 23, width: 14, height: 1, label: "obstacle" },
	{ x: 26, y: 23, width: 1, height: 1, label: "obstacle" },
	{ x: 32, y: 23, width: 1, height: 1, label: "obstacle" },
	{ x: 38, y: 23, width: 3, height: 1, label: "obstacle" },
	{ x: 54, y: 23, width: 2, height: 1, label: "obstacle" },
	{ x: 0, y: 24, width: 2, height: 1, label: "obstacle" },
	{ x: 4, y: 24, width: 14, height: 1, label: "obstacle" },
	{ x: 24, y: 24, width: 1, height: 1, label: "obstacle" },
	{ x: 26, y: 24, width: 1, height: 1, label: "obstacle" },
	{ x: 32, y: 24, width: 1, height: 1, label: "obstacle" },
	{ x: 49, y: 24, width: 7, height: 1, label: "obstacle" },
	{ x: 0, y: 25, width: 2, height: 1, label: "obstacle" },
	{ x: 4, y: 25, width: 15, height: 1, label: "obstacle" },
	{ x: 31, y: 25, width: 1, height: 1, label: "obstacle" },
	{ x: 38, y: 25, width: 3, height: 1, label: "obstacle" },
	{ x: 49, y: 25, width: 7, height: 1, label: "obstacle" },
	{ x: 0, y: 26, width: 2, height: 1, label: "obstacle" },
	{ x: 4, y: 26, width: 2, height: 1, label: "obstacle" },
	{ x: 7, y: 26, width: 2, height: 1, label: "obstacle" },
	{ x: 10, y: 26, width: 2, height: 1, label: "obstacle" },
	{ x: 13, y: 26, width: 2, height: 1, label: "obstacle" },
	{ x: 16, y: 26, width: 1, height: 1, label: "obstacle" },
	{ x: 32, y: 26, width: 5, height: 1, label: "obstacle" },
	{ x: 49, y: 26, width: 7, height: 1, label: "obstacle" },
	{ x: 0, y: 27, width: 2, height: 1, label: "obstacle" },
	{ x: 4, y: 27, width: 1, height: 1, label: "obstacle" },
	{ x: 32, y: 27, width: 5, height: 1, label: "obstacle" },
	{ x: 40, y: 27, width: 5, height: 1, label: "obstacle" },
	{ x: 49, y: 27, width: 7, height: 1, label: "obstacle" },
	{ x: 0, y: 28, width: 2, height: 1, label: "obstacle" },
	{ x: 4, y: 28, width: 1, height: 1, label: "obstacle" },
	{ x: 32, y: 28, width: 5, height: 1, label: "obstacle" },
	{ x: 40, y: 28, width: 1, height: 1, label: "obstacle" },
	{ x: 51, y: 28, width: 5, height: 1, label: "obstacle" },
	{ x: 1, y: 29, width: 1, height: 1, label: "obstacle" },
	{ x: 4, y: 29, width: 2, height: 1, label: "obstacle" },
	{ x: 8, y: 29, width: 1, height: 1, label: "obstacle" },
	{ x: 13, y: 29, width: 1, height: 1, label: "obstacle" },
	{ x: 17, y: 29, width: 1, height: 1, label: "obstacle" },
	{ x: 32, y: 29, width: 5, height: 1, label: "obstacle" },
	{ x: 40, y: 29, width: 1, height: 1, label: "obstacle" },
	{ x: 54, y: 29, width: 2, height: 1, label: "obstacle" },
	{ x: 0, y: 30, width: 2, height: 1, label: "obstacle" },
	{ x: 4, y: 30, width: 3, height: 1, label: "obstacle" },
	{ x: 16, y: 30, width: 2, height: 1, label: "obstacle" },
	{ x: 21, y: 30, width: 3, height: 1, label: "obstacle" },
	{ x: 44, y: 30, width: 1, height: 1, label: "obstacle" },
	{ x: 54, y: 30, width: 2, height: 1, label: "obstacle" },
	{ x: 0, y: 31, width: 2, height: 1, label: "obstacle" },
	{ x: 4, y: 31, width: 6, height: 1, label: "obstacle" },
	{ x: 14, y: 31, width: 4, height: 1, label: "obstacle" },
	{ x: 20, y: 31, width: 2, height: 1, label: "obstacle" },
	{ x: 24, y: 31, width: 1, height: 1, label: "obstacle" },
	{ x: 44, y: 31, width: 1, height: 1, label: "obstacle" },
	{ x: 54, y: 31, width: 2, height: 1, label: "obstacle" },
	{ x: 0, y: 32, width: 2, height: 1, label: "obstacle" },
	{ x: 20, y: 32, width: 1, height: 1, label: "obstacle" },
	{ x: 24, y: 32, width: 1, height: 1, label: "obstacle" },
	{ x: 32, y: 32, width: 5, height: 1, label: "obstacle" },
	{ x: 40, y: 32, width: 5, height: 1, label: "obstacle" },
	{ x: 54, y: 32, width: 2, height: 1, label: "obstacle" },
	{ x: 0, y: 33, width: 2, height: 1, label: "obstacle" },
	{ x: 16, y: 33, width: 1, height: 1, label: "obstacle" },
	{ x: 20, y: 33, width: 1, height: 1, label: "obstacle" },
	{ x: 24, y: 33, width: 1, height: 1, label: "obstacle" },
	{ x: 32, y: 33, width: 5, height: 1, label: "obstacle" },
	{ x: 54, y: 33, width: 2, height: 1, label: "obstacle" },
	{ x: 0, y: 34, width: 3, height: 1, label: "obstacle" },
	{ x: 20, y: 34, width: 1, height: 1, label: "obstacle" },
	{ x: 24, y: 34, width: 1, height: 1, label: "obstacle" },
	{ x: 32, y: 34, width: 4, height: 1, label: "obstacle" },
	{ x: 54, y: 34, width: 2, height: 1, label: "obstacle" },
	{ x: 0, y: 35, width: 2, height: 1, label: "obstacle" },
	{ x: 27, y: 35, width: 1, height: 1, label: "obstacle" },
	{ x: 31, y: 35, width: 5, height: 1, label: "obstacle" },
	{ x: 54, y: 35, width: 2, height: 1, label: "obstacle" },
	{ x: 0, y: 36, width: 2, height: 1, label: "obstacle" },
	{ x: 12, y: 36, width: 1, height: 1, label: "obstacle" },
	{ x: 27, y: 36, width: 1, height: 1, label: "obstacle" },
	{ x: 31, y: 36, width: 5, height: 1, label: "obstacle" },
	{ x: 54, y: 36, width: 2, height: 1, label: "obstacle" },
	{ x: 0, y: 37, width: 2, height: 1, label: "obstacle" },
	{ x: 22, y: 37, width: 1, height: 1, label: "obstacle" },
	{ x: 27, y: 37, width: 1, height: 1, label: "obstacle" },
	{ x: 31, y: 37, width: 19, height: 1, label: "obstacle" },
	{ x: 51, y: 37, width: 5, height: 1, label: "obstacle" },
	{ x: 0, y: 38, width: 2, height: 1, label: "obstacle" },
	{ x: 27, y: 38, width: 1, height: 1, label: "obstacle" },
	{ x: 31, y: 38, width: 25, height: 1, label: "obstacle" },
];

export const TILED_DOORS: Record<number, MapPoint> = {
	5: { x: 23, y: 16 },
};

export const TILED_WARPS: MapWarpDef[] = [
	{ position: { x: 23, y: 8 }, targetMapId: "gym1", targetSpawnId: "gym1-entrance" },
	{ position: { x: 30, y: 7 }, targetMapId: "gym2", targetSpawnId: "gym2-entrance" },
	{ position: { x: 37, y: 8 }, targetMapId: "gym3", targetSpawnId: "gym3-entrance" },
	{ position: { x: 6, y: 7 }, targetMapId: "lab", targetSpawnId: "lab-entrance" },
];

export const TILED_SPAWNS: MapSpawnDef[] = [
	{ id: "gym1-exit", position: { x: 23, y: 9 }, facing: "down" },
	{ id: "gym2-exit", position: { x: 30, y: 8 }, facing: "down" },
	{ id: "gym3-exit", position: { x: 37, y: 9 }, facing: "down" },
	{ id: "lab-exit", position: { x: 6, y: 8 }, facing: "down" },
	{ id: "game-start", position: { x: 29, y: 33 }, facing: "down" },
];

export const TILED_WILD_ZONES: MapEncounterZone[] = [
	{ x: 44, y: 4, width: 9, height: 15 },
];

export const TILED_PORTALS: MapPortalDef[] = [];

export const TILED_ACTABLES: MapActableDef[] = [{"id": 12, "position": {"x": 3, "y": 16}, "facing": "down", "name": "Eric", "message": "I got this house on a crazy good deal."}, {"id": 13, "position": {"x": 14, "y": 15}, "facing": "down", "name": "Hailey", "message": "Mm mm that bread at the market is so tasy."}, {"id": 14, "position": {"x": 21, "y": 31}, "facing": "down", "name": "Ben", "message": "Some people say the mayor is a robot. Maybe that's why she never seems to age."}, {"id": 15, "position": {"x": 41, "y": 18}, "facing": "down", "name": "Billy", "message": "Be careful! The garden is full of Portalmon."}, {"id": 16, "position": {"x": 20, "y": 16}, "facing": "down", "name": "Nurse Karen", "message": "Your Portalmon will be well taken care of in our enrichment center"}, {"id": 17, "position": {"x": 6, "y": 25}, "facing": "down", "name": "bob1", "message": "Fresh cache, picked this morning. Only slightly stale."}, {"id": 18, "position": {"x": 9, "y": 25}, "facing": "down", "name": "bob2", "message": "Two for one on legacy dependencies. No refunds, no support."}, {"id": 20, "position": {"x": 15, "y": 25}, "facing": "down", "name": "bob4", "message": "Everything at this stall is organic, artisanal, and completely untested."}, {"id": 21, "position": {"x": 51, "y": 37}, "facing": "down", "name": "Joe", "message": "Been phishing for days now and no bytes."}, {"id": 22, "position": {"x": 12, "y": 25}, "facing": "down", "name": "bob3", "message": "These tomatoes are heirloom. So is my codebase. Neither is documented."}, {"id": 28, "position": {"x": 48, "y": 20}, "facing": "down", "name": "Sign", "message": "Wild Portalmon ahead. Enter at your own risk!"}, {"id": 30, "position": {"x": 18, "y": 25}, "facing": "down", "name": "Sign", "message": "Farmer's Market"}, {"id": 40, "position": {"x": 17, "y": 3}, "facing": "down", "trainerId": "rey"}, {"id": 41, "position": {"x": 31, "y": 25}, "facing": "down", "name": "Sign", "message": "Welcome to Portal town! East: Beach. Northeast: Wild Portalmon safari. North: Gym battles. Center: Enrichment Center. Northwest: Lab. West: Farmer's Market."}, {"id": 42, "position": {"x": 30, "y": 11}, "facing": "down", "name": "Sign", "message": "Dangerous and tricky gym battles ahead! Make sure you've trained in the safari (east) before entering."}, {"id": 43, "position": {"x": 50, "y": 27}, "facing": "down", "name": "Door", "message": "Locked!"}, {"id": 44, "position": {"x": 5, "y": 14}, "facing": "down", "name": "Door", "message": "Locked!"}, {"id": 45, "position": {"x": 12, "y": 14}, "facing": "down", "name": "Door", "message": "Locked!"}, {"id": 46, "position": {"x": 42, "y": 12}, "facing": "down", "name": "Sign", "message": "Wild Portalmon ahead. Enter at your own risk!"}];
