// Generated by scripts/build-town-map.py from town-layout.json.
// Edit the JSON and rerun the builder; do not hand-edit this file.

export const GENERATED_TOWN_LAYOUT = {
  "width": 56,
  "height": 40,
  "defaultSpawn": {
    "x": 28,
    "y": 37
  },
  "defaultFacing": "up",
  "centerDoor": {
    "x": 27,
    "y": 26
  },
  "centerReturn": {
    "x": 27,
    "y": 27
  },
  "maintenanceTech": {
    "x": 21,
    "y": 27
  },
  "collisionRects": [
    {
      "x": 0,
      "y": 0,
      "width": 2,
      "height": 40,
      "label": "tree line"
    },
    {
      "x": 54,
      "y": 0,
      "width": 2,
      "height": 40,
      "label": "tree line"
    },
    {
      "x": 2,
      "y": 0,
      "width": 22,
      "height": 1,
      "label": "tree line"
    },
    {
      "x": 33,
      "y": 0,
      "width": 21,
      "height": 1,
      "label": "tree line"
    },
    {
      "x": 2,
      "y": 39,
      "width": 25,
      "height": 1,
      "label": "tree line"
    },
    {
      "x": 30,
      "y": 39,
      "width": 24,
      "height": 1,
      "label": "tree line"
    },
    {
      "x": 24,
      "y": 1,
      "width": 9,
      "height": 6,
      "label": "Champion Hall"
    },
    {
      "x": 16,
      "y": 8,
      "width": 7,
      "height": 5,
      "label": "West Gym"
    },
    {
      "x": 16,
      "y": 13,
      "width": 3,
      "height": 1,
      "label": "West Gym"
    },
    {
      "x": 20,
      "y": 13,
      "width": 3,
      "height": 1,
      "label": "West Gym"
    },
    {
      "x": 24,
      "y": 8,
      "width": 7,
      "height": 5,
      "label": "Center Gym"
    },
    {
      "x": 24,
      "y": 13,
      "width": 3,
      "height": 1,
      "label": "Center Gym"
    },
    {
      "x": 28,
      "y": 13,
      "width": 3,
      "height": 1,
      "label": "Center Gym"
    },
    {
      "x": 32,
      "y": 8,
      "width": 7,
      "height": 5,
      "label": "East Gym"
    },
    {
      "x": 32,
      "y": 13,
      "width": 3,
      "height": 1,
      "label": "East Gym"
    },
    {
      "x": 36,
      "y": 13,
      "width": 3,
      "height": 1,
      "label": "East Gym"
    },
    {
      "x": 23,
      "y": 20,
      "width": 9,
      "height": 6,
      "label": "Portalmon Center"
    },
    {
      "x": 23,
      "y": 26,
      "width": 4,
      "height": 1,
      "label": "Portalmon Center"
    },
    {
      "x": 28,
      "y": 26,
      "width": 4,
      "height": 1,
      "label": "Portalmon Center"
    },
    {
      "x": 4,
      "y": 17,
      "width": 6,
      "height": 5,
      "label": "townhouse"
    },
    {
      "x": 12,
      "y": 18,
      "width": 6,
      "height": 5,
      "label": "townhouse"
    },
    {
      "x": 4,
      "y": 29,
      "width": 6,
      "height": 5,
      "label": "townhouse"
    },
    {
      "x": 12,
      "y": 30,
      "width": 6,
      "height": 5,
      "label": "townhouse"
    },
    {
      "x": 39,
      "y": 19,
      "width": 12,
      "height": 5,
      "label": "park pond"
    },
    {
      "x": 39,
      "y": 26,
      "width": 12,
      "height": 3,
      "label": "park pond"
    },
    {
      "x": 1,
      "y": 2,
      "width": 3,
      "height": 4,
      "label": "tree"
    },
    {
      "x": 5,
      "y": 3,
      "width": 3,
      "height": 4,
      "label": "tree"
    },
    {
      "x": 46,
      "y": 3,
      "width": 3,
      "height": 4,
      "label": "tree"
    },
    {
      "x": 51,
      "y": 5,
      "width": 3,
      "height": 4,
      "label": "tree"
    },
    {
      "x": 1,
      "y": 10,
      "width": 3,
      "height": 4,
      "label": "tree"
    },
    {
      "x": 48,
      "y": 12,
      "width": 3,
      "height": 4,
      "label": "tree"
    },
    {
      "x": 52,
      "y": 16,
      "width": 3,
      "height": 4,
      "label": "tree"
    },
    {
      "x": 35,
      "y": 19,
      "width": 3,
      "height": 4,
      "label": "tree"
    },
    {
      "x": 52,
      "y": 27,
      "width": 3,
      "height": 4,
      "label": "tree"
    },
    {
      "x": 1,
      "y": 35,
      "width": 3,
      "height": 4,
      "label": "tree"
    },
    {
      "x": 6,
      "y": 35,
      "width": 3,
      "height": 4,
      "label": "tree"
    },
    {
      "x": 47,
      "y": 35,
      "width": 3,
      "height": 4,
      "label": "tree"
    },
    {
      "x": 52,
      "y": 34,
      "width": 3,
      "height": 4,
      "label": "tree"
    },
    {
      "x": 20,
      "y": 19,
      "width": 1,
      "height": 1,
      "label": "town fountain"
    },
    {
      "x": 14,
      "y": 14,
      "width": 1,
      "height": 1,
      "label": "gym-sign"
    },
    {
      "x": 22,
      "y": 14,
      "width": 1,
      "height": 1,
      "label": "gym-sign"
    },
    {
      "x": 40,
      "y": 14,
      "width": 1,
      "height": 1,
      "label": "gym-sign"
    },
    {
      "x": 33,
      "y": 23,
      "width": 1,
      "height": 1,
      "label": "center-sign"
    },
    {
      "x": 36,
      "y": 32,
      "width": 6,
      "height": 4,
      "label": "cargo"
    },
    {
      "x": 44,
      "y": 32,
      "width": 5,
      "height": 4,
      "label": "machinery"
    }
  ],
  "interactions": [
    {
      "position": {
        "x": 19,
        "y": 13
      },
      "kind": "gym",
      "gymSlot": 0
    },
    {
      "position": {
        "x": 27,
        "y": 13
      },
      "kind": "gym",
      "gymSlot": 1
    },
    {
      "position": {
        "x": 35,
        "y": 13
      },
      "kind": "gym",
      "gymSlot": 2
    }
  ]
} as const;
